import { z } from "zod";

export const ingestSchema = z.object({
  source: z.enum(["firewall", "api", "crowdstrike", "aws", "m365", "ad", "network"]),
  "@timestamp": z.string().optional(),
  tenant: z.string().optional(),
  event_id: z.number().optional(),
  severity: z.number().min(0).max(10).optional(),
  tags: z.array(z.string()).optional(),
  msg: z.string().optional(),
  http_method: z.string().optional(),
  url: z.string().optional(),
  status_code: z.number().optional(),
  src_ip: z.string().optional(),
  src_port: z.number().optional(),
  dst_ip: z.string().optional(),
  dst_port: z.number().optional(),
  protocol: z.string().optional(),
  user: z.string().optional(),
  host: z.string().optional(),
  process: z.string().optional(),
  action: z.string().optional(),
  event_type: z.string().optional(),
  event_subtype: z.string().optional(),
  vendor: z.string().optional(),
  product: z.string().optional(),
  rule_name: z.string().optional(),
  rule_id: z.string().optional(),
  cloud: z.object({
    account_id: z.string().optional(),
    region: z.string().optional(),
    service: z.string().optional(),
  }).optional(),
});
